-- CREATE DATABASE

CREATE TABLE public."questionary" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name_enterprise" varchar(50) NOT NULL,
    "updated_at" timestamp NOT NULL,
    "created_at" timestamp NOT NULL,
    "nps_value" int4 NOT NULL DEFAULT 0,	
	CONSTRAINT "PK_Questionary" PRIMARY KEY ("id")
);

CREATE TABLE public."user" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,
    "mail" varchar(50) NOT NULL,
    "password" varchar(50) NOT NULL,
    "phone" varchar(22) NOT NULL,	
    "is_admin" bool NOT NULL DEFAULT false,
	CONSTRAINT "PK_User" PRIMARY KEY ("id")
);

CREATE TABLE public."nps_history" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "questionary_id" int4 NOT NULL,	
    "user_id" int4 NOT NULL,	
	"nps_value" int4 NOT NULL,	
    "updated_at" timestamp NOT NULL,
	CONSTRAINT "PK_NpsHistory" PRIMARY KEY ("id"),
    CONSTRAINT "FK_NpsHistory_Questionary_Id" FOREIGN KEY ("questionary_id") REFERENCES public."questionary"("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_NpsHistory_User_Id" FOREIGN KEY ("user_id") REFERENCES public."user"("id") ON DELETE RESTRICT
);

CREATE TABLE public."question" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "questionary_id" int4 NOT NULL,
    "name" varchar(50) NOT NULL,	
	"description" varchar(50) NOT NULL,
    "updated_at" timestamp NOT NULL,
    "created_at" timestamp NOT NULL,
    "constant_factor" int4 NOT NULL,
    "is_multiple" bool NOT NULL DEFAULT false,	
	CONSTRAINT "PK_Question" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Question_Questionary_Id" FOREIGN KEY ("questionary_id") REFERENCES public."questionary"("id") ON DELETE RESTRICT
);	

CREATE TABLE public."questionary_user" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int4 NOT NULL,
    "questionary_id" int4 NOT NULL,		
	CONSTRAINT "PK_QuestionaryUser" PRIMARY KEY ("id"),
    CONSTRAINT "FK_QuestionaryUser_User_Id" FOREIGN KEY ("user_id") REFERENCES public."user"("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_QuestionaryUser_Questionary_Id" FOREIGN KEY ("questionary_id") REFERENCES public."questionary"("id") ON DELETE RESTRICT
);

CREATE TABLE public."enterprise" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int4 NOT NULL,	
	"name" varchar(50) NOT NULL,	
    "mail" varchar(50) NOT NULL,
    "phone" varchar(22) NOT NULL,
	CONSTRAINT "PK_Enterprise" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Enterprise_User_Id" FOREIGN KEY ("user_id") REFERENCES public."user"("id") ON DELETE RESTRICT
);

CREATE TABLE public."answer" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "questionary_id" int4 NOT NULL,	
    "question_id" int4 NOT NULL,	
	"name" varchar(50) NOT NULL,
    "updated_at" timestamp NOT NULL,
    "created_at" timestamp NOT NULL,
    "value" int4 NOT NULL,	
	CONSTRAINT "PK_Answer" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Answer_Questionary_Id" FOREIGN KEY ("questionary_id") REFERENCES public."questionary"("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Answer_Question_Id" FOREIGN KEY ("question_id") REFERENCES public."question"("id") ON DELETE RESTRICT
);
